apiVersion: v1
kind: Pod
metadata:
  name: jonathan-jupyter-notebook
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
    command: ["sh", "-c", "jupyter notebook --ip='0.0.0.0' && sleep infinity"]
    resources:
      limits:
        memory: 20Gi
        cpu: "16"
        nvidia.com/gpu: 1
      requests:
        memory: 20Gi
        cpu: "2"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /pvcvolume
      name: pvc
  restartPolicy: Never
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: jonathan-nuscenes

