apiVersion: batch/v1
kind: Job
metadata:
  name: jonathan-github-setup
spec:
  template:
    spec:
      containers:
      - name: jonathan-github-setup
        image: ubuntu
        command:
        - sh
        - -c
        - "apt-get update && apt-get --assume-yes install git && cd /pvcvolume && git clone https://github.com/Slugbotics/cruz-control"
        volumeMounts:
        - name: pvcvolume
          mountPath: /pvcvolume
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 1Gi
            cpu: "1"
      volumes:
      - name: pvcvolume
        persistentVolumeClaim:
          claimName: jonathan-nuscenes
      restartPolicy: Never
  backoffLimit: 1

