apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jonathan-nuscenes-block
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
