apiVersion: batch/v1
kind: Job
metadata:
  name: jonathan-download-nuscenes
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
        command:
        - sh
        - -c
        - "cd /pvcvolume/cruz-control/nuscenes && apt-get update && apt-get --assume-yes install git && git pull && python download_nuscenes.py"
        volumeMounts:
        - name: pvcvolume
          mountPath: /pvcvolume
        resources:
          limits:
            memory: 16Gi
            cpu: "5"
          requests:
            memory: 8Gi
            cpu: "2"
      volumes:
      - name: pvcvolume
        persistentVolumeClaim:
          claimName: jonathan-nuscenes
      restartPolicy: Never
  backoffLimit: 5
