apiVersion: v1
kind: Pod
metadata:
  name: jonathan-nuscenes-pod
spec:
  containers:
  - name: mypod
    image: ubuntu
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 16Gi
        cpu: 2
      requests:
        memory: 16Gi
        cpu: 2
    volumeMounts:
    - mountPath: /pvcvolume
      name: examplevol
  volumes:
  - name: examplevol
    persistentVolumeClaim:
      claimName: jonathan-nuscenes
