apiVersion: v1
kind: Pod
metadata:
  name: jonathan-nuscenes-pod
spec:
  containers:
  - name: mypod
    image: ubuntu
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 1.5Gi
        cpu: "2"
      requests:
        memory: 1.5Gi
        cpu: "2"
    volumeMounts:
    - mountPath: /pvcvolume
      name: jonathan-nuscenes
  volumes:
  - name: jonathan-nuscenes
    persistentVolumeClaim:
      claimName: jonathan-nuscenes
