apiVersion: v1
kind: Pod
metadata:
  name: jonathan-nuscenes-pod
spec:
  containers:
  - name: mypod
    image: pytorch/pytorch
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 32Gi
        cpu: "8"
      requests:
        memory: 32Gi
        cpu: "8"
    volumeMounts:
    - mountPath: /pvcvolume
      name: jonathan-nuscenes
  volumes:
  - name: jonathan-nuscenes
    persistentVolumeClaim:
      claimName: jonathan-nuscenes
